# Generated by Django 3.1 on 2020-09-02 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('total_arrecado', models.FloatField()),
                ('total_gasto', models.FloatField()),
                ('total_gasto_comida', models.FloatField()),
                ('total_gasto_bebida', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_bebe', models.BooleanField(default=True)),
                ('convidado_bebe', models.BooleanField(default=True)),
                ('id_convidado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.convidado')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.funcionario')),
            ],
            options={
                'unique_together': {('id_evento', 'id_funcionario')},
            },
        ),
    ]
