# Generated by Django 3.1 on 2020-09-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200903_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convidado',
            old_name='id_funcionario',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='evento_funcionario',
            old_name='id_convidado',
            new_name='convidado',
        ),
        migrations.RenameField(
            model_name='evento_funcionario',
            old_name='id_evento',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='evento_funcionario',
            old_name='id_funcionario',
            new_name='funcionario',
        ),
        migrations.AlterUniqueTogether(
            name='evento_funcionario',
            unique_together={('evento', 'funcionario')},
        ),
    ]
