# Generated by Django 3.1 on 2020-09-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200903_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='total_arrecado',
            new_name='total_arrecadado',
        ),
    ]
